version: 4
#permit_join: true
frontend:
  package: zigbee2mqtt-windfront
  enabled: true
  port: 8085
  host: 0.0.0.0
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
advanced:
  log_level: debug
  channel: 11
  network_key:
    - 48
    - 218
    - 101
    - 18
    - 134
    - 18
    - 7
    - 205
    - 66
    - 240
    - 222
    - 1
    - 15
    - 77
    - 240
    - 168
  pan_id: 49050
  ext_pan_id:
    - 18
    - 39
    - 181
    - 151
    - 185
    - 189
    - 167
    - 162
serial:
  port: tcp://192.168.1.242:6638
  baudrate: 115200
# Disable Green LED
  disable_led: false
  adapter: ezsp

